pipeline {
    agent any

    environment {
        APP_ENV = 'staging'
    }

    stages {
        stage('Build') {
            options {
                retry(3)
            }
            steps {
                echo "Environment is: ${env.APP_ENV}"
                echo "Executing make build..."
            }
        }

        stage('Test') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    echo "Executing make test..."
                }
            }
        }
    }
}
